"""add document_name to document_chunks

Revision ID: d349caf910f5
Revises: e21e460ae261
Create Date: 2026-07-22 16:55:39.571351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd349caf910f5'
down_revision: Union[str, Sequence[str], None] = 'e21e460ae261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('document_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'document_name')
    # ### end Alembic commands ###
